// Flat C exports observed in twinapi.appcore.dll. Unknown ABIs are intentionally not declared.
// Validated dialects: ISO C17/C23/C26 draft and Windissect C20 (C ABI under C++20).
#pragma once
#ifndef TWINAPI_APPCORE_C_H
#define TWINAPI_APPCORE_C_H
#if defined(__cplusplus)
#  if __cplusplus < 202002L
#    define WINDISSECT_C20_PROFILE 0
#  else
#    define WINDISSECT_C20_PROFILE 1
#  endif
extern "C" {
#else
#  if defined(__STDC_VERSION__) && __STDC_VERSION__ < 201710L
#    error "Windissect C output requires C17 or newer"
#  endif
#  define WINDISSECT_C20_PROFILE 0
#  define WINDISSECT_C_STANDARD __STDC_VERSION__
#endif

// Export: #ordinal7 (ABI unverified)
// Export: CoreQueryWindowService (ABI unverified)
// Export: #ordinal9 (ABI unverified)
// Export: CoreUnregisterWindowService (ABI unverified)
// Export: #ordinal8 (ABI unverified)
// Export: CoreIsWindowServiceSupported (ABI unverified)
// Export: #ordinal6 (ABI unverified)
// Export: CoreRegisterWindowService (ABI unverified)
// Export: PsmBlockAppStateChangeCompletion (ABI unverified)
// Export: PsmUnblockAppStateChangeCompletion (ABI unverified)
// Export: PsmWaitForAppResume (ABI unverified)
// Export: #ordinal504 (ABI unverified)
// Export: DesktopLegacySetTitle (ABI unverified)
// Export: #ordinal10 (ABI unverified)
// Export: CoreUnregisterAllWindowServices (ABI unverified)
// Export: PsmQueryCurrentAppState (ABI unverified)
// Export: PsmRegisterAppStateChangeNotification (ABI unverified)
// Export: PsmTimerCleanup (ABI unverified)
// Export: PsmTimerStart (ABI unverified)
// Export: #ordinal2 (ABI unverified)
// Export: CoreQueryApplicationService (ABI unverified)
// Export: DllGetClassObject (ABI unverified)
// Export: BiPtQuerySystemStateBroadcastChannels (ABI unverified)
// Export: BiPtEnumerateWorkItemsForPackageName (ABI unverified)
// Export: BiPtDisassociateWorkItemEx (ABI unverified)
// Export: BiPtActivateInBackgroundEx (ABI unverified)
// Export: BiPtSignalEventEx (ABI unverified)
// Export: BiPtCreateEventForPackageName (ABI unverified)
// Export: BiPtEnumerateBrokeredEvents (ABI unverified)
// Export: BiPtDeleteEvent (ABI unverified)
// Export: BiPtCreateEventForApp (ABI unverified)
// Export: BiPtAssociateActivationProxy (ABI unverified)
// Export: BiPtQueryWorkItem (ABI unverified)
// Export: BiPtQueryWorkItemStatusStateName (ABI unverified)
// Export: BiPtQueryBrokeredEvent (ABI unverified)
// Export: #ordinal3 (ABI unverified)
// Export: CoreIsApplicationServiceSupported (ABI unverified)
// Export: DllCanUnloadNow (ABI unverified)
// Export: UnregisterAppStateChangeNotification (ABI unverified)
// Export: PsmUnregisterAppStateChangeNotification (ABI unverified)
// Export: #ordinal4 (ABI unverified)
// Export: CoreUnregisterApplicationService (ABI unverified)
// Export: #ordinal12 (ABI unverified)
// Export: IsImmersiveWindow (ABI unverified)
// Export: DllGetActivationFactory (ABI unverified)
// Export: BiChangeUserState (ABI unverified)
// Export: BiNotifyNewSessionComplete (ABI unverified)
// Export: BiChangeApplicationStateForPackageNameForUser (ABI unverified)
// Export: #ordinal1 (ABI unverified)
// Export: CoreRegisterApplicationService (ABI unverified)
// Export: PsmTimerInitialize (ABI unverified)
// Export: BiNotifyNewSession (ABI unverified)
// Export: PsmRegisterKeyNotification (ABI unverified)
// Export: BiPlmFreeMemory (ABI unverified)
// Export: BiPtFreeMemory (ABI unverified)
// Export: MIDL_user_free (ABI unverified)
// Export: BiNotifyNewUser (ABI unverified)
// Export: BiUpdateBackgroundAccessApplicationsForUser (ABI unverified)
// Export: BiUpdateLockScreenApplications (ABI unverified)
// Export: PsmInitializeExtension (ABI unverified)
// Export: RegisterAppConstrainedChangeNotification (ABI unverified)
// Export: `anonymous namespace'::UIViewSettings::InternalGetTrustLevel (ABI unverified)
// Export: winrt::impl::root_implements<std::experimental::coroutine_traits<winrt::Windows::Foundation::IAsyncOperation<enum winrt::Windows::UI::Shell::ShareWindowCommand>,<lambda_ca40ea92cb4716a5a609c22fd370495a> const *>::promise_type,winrt::Windows::Foundation::IAsyncOperation<enum winrt::Windows::UI::Shell::ShareWindowCommand>,winrt::Windows::Foundation::IAsyncInfo>::GetTrustLevel (ABI unverified)
// Export: winrt::impl::root_implements<std::experimental::coroutine_traits<winrt::Windows::Foundation::IAsyncOperation<enum winrt::Windows::UI::Shell::ShareWindowCommand>,<lambda_e94fec98e21d3c9eb1d466073af240f9> const *>::promise_type,winrt::Windows::Foundation::IAsyncOperation<enum winrt::Windows::UI::Shell::ShareWindowCommand>,winrt::Windows::Foundation::IAsyncInfo>::GetTrustLevel (ABI unverified)
// Export: winrt::impl::root_implements<std::experimental::coroutine_traits<winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::UI::WindowId> >,<lambda_48801d1e8d76bfb678215d4d54b21c5a> const *>::promise_type,winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::UI::WindowId> >,winrt::Windows::Foundation::IAsyncInfo>::GetTrustLevel (ABI unverified)
// Export: winrt::impl::root_implements<std::experimental::coroutine_traits<winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::UI::WindowId> >,<lambda_77cd4f443ba0fe25b6e04ba04b929349> const *>::promise_type,winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::UI::WindowId> >,winrt::Windows::Foundation::IAsyncInfo>::GetTrustLevel (ABI unverified)
// Export: BiChangeApplicationStateForPackageName (ABI unverified)
// Export: BiChangeSessionState (ABI unverified)
// Export: <lambda_276d34235ff4442b3c5766550117e8c2>::<lambda_invoker_cdecl> (ABI unverified)
// Export: PsmRegisterManagerType (ABI unverified)
// Export: UnregisterAppConstrainedChangeNotification (ABI unverified)
// Export: wil_StagingConfig_LogFeatureProcessUsage (ABI unverified)
// Export: wistd::__function::__func<<lambda_34f0ffdfbbc25d8ef114b9cdd4c72719>,void __cdecl(void)>::destroy (ABI unverified)
// Export: wistd::__function::__func<<lambda_3e647aa0437d351ae59f69f2af1884d1>,void __cdecl(void)>::destroy (ABI unverified)
// Export: wistd::__function::__func<<lambda_4739ada28cc37b090dbeff54ed7bf284>,long __cdecl(Windows::ApplicationModel::Core::CoreApplicationViewAgileContainer * *)>::destroy (ABI unverified)
// Export: wistd::__function::__func<<lambda_70cb17ac41a175bacf762f24ac906eab>,long __cdecl(Windows::ApplicationModel::Core::CoreApplicationViewAgileContainer * *)>::destroy (ABI unverified)
// Export: wistd::__function::__func<<lambda_9b5829da5ef594482e949cc74239d431>,void __cdecl(void)>::destroy (ABI unverified)
// Export: PsmShutdownApplication (ABI unverified)
// Export: #ordinal501 (ABI unverified)
// Export: BiSessionSinkCleanup (ABI unverified)
// Export: BiSessionSinkCreate (ABI unverified)
// Export: PsmIsProcessInApplication (ABI unverified)
// Export: #ordinal502 (ABI unverified)
// Export: CreateApplicationViewTitleBar (ABI unverified)
// Export: #ordinal503 (ABI unverified)
// Export: DesktopLegacySetPreferredMinSize (ABI unverified)
// Export: #ordinal500 (ABI unverified)
// Export: ValidateSystemShutdown (ABI unverified)
// Export: #ordinal5 (ABI unverified)
// Export: CoreUnregisterAllApplicationServices (ABI unverified)
// Export: #ordinal11 (ABI unverified)
// Export: CoreEnumWindowServices (ABI unverified)
// Export: #ordinal13 (ABI unverified)
// Export: CoreQueryWindowServiceEx (ABI unverified)
// Export: #ordinal14 (ABI unverified)
// Export: CoreRegisterWindowServiceWithOptions (ABI unverified)
// Export: BiActivateWorkItemForUser (ABI unverified)
// Export: BiChangeApplicationStateForPsmKey (ABI unverified)
// Export: BiChangeApplicationStateForPsmKeyForUser (ABI unverified)
// Export: BiEnumerateWorkItemsForPackageNameAndUser (ABI unverified)
// Export: BiGetActiveBackgroundTasksEvent (ABI unverified)
// Export: BiGetActiveBackgroundTasksEventForUser (ABI unverified)
// Export: BiGetCancellationTimeoutInMs (ABI unverified)
// Export: BiIsApplicationTerminateSensitive (ABI unverified)
// Export: BiIsApplicationTerminateSensitiveForUser (ABI unverified)
// Export: BiQueryWorkItemForUser (ABI unverified)
// Export: BiResetActiveSessionForPackage (ABI unverified)
// Export: BiResetActiveUserForPackage (ABI unverified)
// Export: BiSetActiveSessionForPackage (ABI unverified)
// Export: BiSetActiveUserForPackage (ABI unverified)
// Export: BiTerminateApplicationHost (ABI unverified)
// Export: BiTerminateApplicationHost2 (ABI unverified)
// Export: BiTerminateApplicationHostForUser (ABI unverified)
// Export: BiPtActivateDeferredWorkItem (ABI unverified)
// Export: BiPtActivateInBackground (ABI unverified)
// Export: BiPtActivateWorkItem (ABI unverified)
// Export: BiPtAssociateApplicationEntryPoint (ABI unverified)
// Export: BiPtAssociateApplicationExtensionClass (ABI unverified)
// Export: BiPtCancelWorkItem (ABI unverified)
// Export: BiPtCancelWorkItemEx (ABI unverified)
// Export: BiPtCreateEvent (ABI unverified)
// Export: BiPtDisableWorkItem (ABI unverified)
// Export: BiPtDisassociateWorkItem (ABI unverified)
// Export: BiPtEnableWorkItem (ABI unverified)
// Export: BiPtEnumerateBrokeredEventsEx (ABI unverified)
// Export: BiPtEnumerateWorkItemsForPackageNameEx (ABI unverified)
// Export: BiPtGetStatusStateNameFromBrokerEventId (ABI unverified)
// Export: BiPtQueryBrokerEventId (ABI unverified)
// Export: BiPtQueryWorkItemEx (ABI unverified)
// Export: BiPtSignalEvent (ABI unverified)
// Export: BiPtSignalMultipleEvents (ABI unverified)
// Export: BiPtSignalTriggerEvent (ABI unverified)
// Export: BiPtSignalTriggerEventEx (ABI unverified)
// Export: PsmApplyTaskCompletion (ABI unverified)
// Export: PsmGetSessionInfo (ABI unverified)
// Export: PsmRegisterDynamicProcess (ABI unverified)
// Export: PsmDisconnect (ABI unverified)
// Export: PsmIsProcessInApplication2 (ABI unverified)
// Export: PsmQueryApplicationInformation (ABI unverified)
// Export: PsmQueryApplicationInformation2 (ABI unverified)
// Export: PsmQueryApplicationInterferenceCount (ABI unverified)
// Export: PsmQueryApplicationInterferenceCount2 (ABI unverified)
// Export: PsmQueryApplicationProperties (ABI unverified)
// Export: PsmQueryApplicationProperties2 (ABI unverified)
// Export: PsmQueryApplicationProperties3 (ABI unverified)
// Export: PsmQueryApplicationPropertiesByUser (ABI unverified)
// Export: PsmQueryApplicationResourceUsage (ABI unverified)
// Export: PsmQueryApplicationResourceUsage2 (ABI unverified)
// Export: PsmQueryMaxMemoryUsage (ABI unverified)
// Export: PsmQueryMaxMemoryUsage2 (ABI unverified)
// Export: PsmQueryMemoryUsage (ABI unverified)
// Export: PsmQueryMemoryUsage2 (ABI unverified)
// Export: PsmQuerySharedCommitByUser (ABI unverified)
// Export: PsmQueryTaskCompletionInformation (ABI unverified)
// Export: PsmQueryTaskCompletionInformation2 (ABI unverified)
// Export: PsmResetMaxMemoryUsage (ABI unverified)
// Export: PsmResetMaxMemoryUsage2 (ABI unverified)
// Export: PsmResetMaxMemoryUsageByUser (ABI unverified)
// Export: PsmSetApplicationPriority (ABI unverified)
// Export: PsmSetApplicationPriority2 (ABI unverified)
// Export: PsmSetApplicationProperties (ABI unverified)
// Export: PsmSetApplicationProperties2 (ABI unverified)
// Export: PsmSetApplicationProperties3 (ABI unverified)
// Export: PsmSetApplicationPropertiesByUser (ABI unverified)
// Export: PsmQueryApplicationList (ABI unverified)
// Export: PsmQueryApplicationList2 (ABI unverified)
// Export: PsmQueryMemoryUsageByUser (ABI unverified)
// Export: PsmQueryProcessList (ABI unverified)
// Export: PsmQueryProcessList2 (ABI unverified)
// Export: PsmRegisterApplicationNotification (ABI unverified)
// Export: PsmRegisterApplicationNotification2 (ABI unverified)
// Export: PsmSetApplicationState (ABI unverified)
// Export: PsmSetApplicationState2 (ABI unverified)
// Export: PsmQueryApplicationResourceUsageForTimer (ABI unverified)
// Export: PsmRegisterAppPriorityNotification (ABI unverified)
// Export: PsmTimerElapsedResourceTimeGet (ABI unverified)
// Export: PsmTimerRemainingResourceTimeGet (ABI unverified)
// Export: RegisterAppStateChangeNotification (ABI unverified)

#ifdef __cplusplus
} // extern "C"
#endif
#endif // TWINAPI_APPCORE_C_H
